- platform: integration
  source: sensor.lounge_entertainment_white_difference_power
  name: Entertainment White Difference
  unique_id: lounge_entertainment_white_difference_energy
  unit_prefix: k
  round: 3
  method: trapezoidal